name: 编译玩客云OneCloud S805 LEDE固件
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  GITHUB_URL: https://mirror.ghproxy.com/https://github.com

jobs:
  build-firmware:
    runs-on: ubuntu-22.04
    steps:
      - name: 安装编译依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev gawk flex bison git libssl-dev \
          libelf-dev u-boot-tools mkimage ccache device-tree-compiler

      - name: 拉取 LEDE 源码
        run: git clone ${{ env.GITHUB_URL }}/coolsnowwolf/lede.git lede

      - name: 进入源码目录
        working-directory: ./lede
        run: |
          # 替换Github地址防止超时
          sed -i "s|https://github.com|${{ env.GITHUB_URL }}|g" feeds.conf.default
          # 添加插件源
          echo "src-git helloworld ${{ env.GITHUB_URL }}/fw876/helloworld.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 自动导入玩客云设备补丁
        working-directory: ./lede
        run: |
          git clone ${{ env.GITHUB_URL }}/wutongxinwei/onecloud-meson8b-patch.git patch
          cp -r patch/target/linux/amlogic/meson8b/* target/linux/amlogic/meson8b/

      - name: 写入预编译配置
        working-directory: ./lede
        run: |
          cat > .config <<'EOT'
CONFIG_TARGET_amlogic=y
CONFIG_TARGET_amlogic_meson8b=y
CONFIG_TARGET_amlogic_meson8b_DEVICE_onecloud_m201_1G=y
CONFIG_TARGET_ROOTFS_EXT4FS=y
CONFIG_TARGET_IMAGES_GZIP=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_docker=y
CONFIG_PACKAGE_luci-app-dockerman=y
EOT
          make defconfig

      - name: 预下载全部源码包
        working-directory: ./lede
        run: make download -j$(nproc)

      - name: 开始编译固件
        working-directory: ./lede
        run: make -j$(nproc) V=s

      - name: 保存固件到工件
        uses: actions/upload-artifact@v4
        with:
          name: OneCloud-S805-Firmware
          path: lede/bin/targets/amlogic/meson8b/*.img*

      - name: 自动发布Release
        uses: softprops/action-gh-release@v2
        with:
          files: lede/bin/targets/amlogic/meson8b/*.img*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
